# Site settings
name: Divyang Dankhara
title: Divyang Dankhara | Full Stack Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: divyangdankhara.com
baseurl: ''
email: divyangdankhara@outlook.com
logo: https://divyangdankhara.github.io/img/emojis/technologist.png
resume: 
social:
  - title: email
    url: mailto:divyangdankhara007@outlook.com
  - title: github
    url: https://github.com/divyangdankhara
  - title: linkedin
    url: https://www.linkedin.com/in/divyangdankhara

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
